version: '3.4'
services:
  react-app:
    container_name: react-app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/app'
    expose:
      - 3000
    ports:
      - 3000:80
      - 443:443
